#!/usr/bin/env python3
"""Build the static article pages from the markdown sources.

    articles/<slug>.md  ->  article/<slug>/index.html
    (all articles)      ->  article/index.html

Each source starts with front matter:

    ---
    author: Adam Byle
    date: September 29, 2026
    ---

    # Title of the article

    Body...

Optional front-matter keys: `title` (otherwise the first "# " heading is
used), `description` (otherwise the first paragraph), and `draft: true` to
leave an article unpublished.

Typography is cleaned up on the way through: straight quotes become curly
quotes, "--" and "---" become em dashes, and "..." becomes an ellipsis. Code
spans, code blocks, and URLs are left untouched.

Usage:
    python scripts/build_articles.py            # build from the working tree
    python scripts/build_articles.py --staged   # build from the git index
                                                # (used by the pre-commit hook)

Only the Python standard library is used, so there is nothing to install.
"""

import argparse
import html
import os
import re
import shutil
import subprocess
import sys
from datetime import date, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_DIR = "articles"
OUTPUT_DIR = "article"
STYLESHEET = "style.css"
GENERATED_MARKER = "Generated by scripts/build_articles.py"

FONTS_URL = (
    "https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,400;0,500;"
    "0,600;0,700;1,400&family=Fraunces:ital,opsz,wght,SOFT@0,9..144,400..700,"
    "100;1,9..144,400..700,100&display=swap"
)


# ---------------------------------------------------------------------------
# Reading sources
# ---------------------------------------------------------------------------


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, check=True
    ).stdout


def list_sources(staged):
    if staged:
        out = git("ls-files", "-z", "--", f"{SOURCE_DIR}/*.md").decode("utf-8")
        return sorted(p for p in out.split("\0") if p)
    folder = os.path.join(ROOT, SOURCE_DIR)
    if not os.path.isdir(folder):
        return []
    return sorted(
        f"{SOURCE_DIR}/{name}" for name in os.listdir(folder) if name.endswith(".md")
    )


def read_source(path, staged):
    if staged:
        data = git("show", f":{path}")
    else:
        with open(os.path.join(ROOT, path), "rb") as f:
            data = f.read()
    return data.decode("utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")


def asset_version(path):
    """Short hash of the staged asset, matching the pre-commit stamp."""
    try:
        return git("rev-parse", "--short=7", f":{path}").decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


# ---------------------------------------------------------------------------
# Typography
# ---------------------------------------------------------------------------

OPENING_CONTEXT = set(" \t\n([{—–-/")


def smarten(text):
    """Curly quotes, em dashes, and ellipses for plain (non-code) text."""
    text = text.replace("---", "—").replace("--", "—")
    text = text.replace("...", "…")

    # Abbreviated years like '90s take an apostrophe, not an opening quote.
    text = re.sub(r"'(?=\d\ds\b)", "’", text)

    out = []
    for i, ch in enumerate(text):
        prev = text[i - 1] if i else " "
        opening = prev in OPENING_CONTEXT or prev in "“‘"
        if ch == '"':
            out.append("“" if opening else "”")
        elif ch == "'":
            out.append("‘" if opening else "’")
        else:
            out.append(ch)
    return "".join(out)


# ---------------------------------------------------------------------------
# Inline markdown
# ---------------------------------------------------------------------------

PH_START = 0xE000  # Private-use characters stand in for protected spans.


def render_inline(text):
    protected = []

    def protect(rendered):
        protected.append(rendered)
        return chr(PH_START + len(protected) - 1)

    # Backslash escapes, e.g. \* or \_ for literal characters.
    text = re.sub(
        r"\\([\\`*_{}\[\]()#+\-.!\"'<>])",
        lambda m: protect(html.escape(m.group(1))),
        text,
    )
    # Code spans are kept verbatim.
    text = re.sub(
        r"(`+)(.+?)\1",
        lambda m: protect(f"<code>{html.escape(m.group(2).strip())}</code>"),
        text,
    )
    # Autolinks: <https://example.com>
    text = re.sub(
        r"<(https?://[^>\s]+)>",
        lambda m: protect(
            f'<a href="{html.escape(m.group(1))}">{html.escape(m.group(1))}</a>'
        ),
        text,
    )
    # Link destinations: [text](url) keeps the text for normal processing.
    text = re.sub(
        r"\]\(\s*([^)\s]+)\s*\)",
        lambda m: "](" + protect(html.escape(m.group(1))) + ")",
        text,
    )

    text = smarten(text)
    text = html.escape(text, quote=False)

    text = re.sub(r"\*\*(?=\S)(.+?)(?<=\S)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"__(?=\S)(.+?)(?<=\S)__", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![\w*])\*(?=\S)(.+?)(?<=\S)\*(?![\w*])", r"<em>\1</em>", text)
    text = re.sub(r"(?<![\w_])_(?=\S)(.+?)(?<=\S)_(?![\w_])", r"<em>\1</em>", text)

    def link(m):
        href = protected[ord(m.group(2)) - PH_START]
        return f'<a href="{href}">{m.group(1)}</a>'

    text = re.sub(r"\[([^\]]+)\]\(([-])\)", link, text)

    # Restore protected spans (they may nest, so repeat until stable).
    pattern = re.compile(r"[-]")
    while pattern.search(text):
        text = pattern.sub(lambda m: protected[ord(m.group(0)) - PH_START], text)
    return text


def plain_text(rendered):
    """Strip tags from rendered inline HTML (for titles and descriptions)."""
    return html.unescape(re.sub(r"<[^>]+>", "", rendered))


# ---------------------------------------------------------------------------
# Block markdown
# ---------------------------------------------------------------------------


def slugify(text):
    text = plain_text(text).lower()
    text = re.sub(r"[‘’'\"“”]", "", text)
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-")


LIST_ITEM = re.compile(r"^\s*([-*+]|\d+[.)])\s+(.*)$")
HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
RULE = re.compile(r"^\s*([-*_])(\s*\1){2,}\s*$")


def render_blocks(lines):
    """Render markdown lines to HTML. Returns (html, headings)."""
    out = []
    headings = []
    i = 0

    def is_block_start(line):
        return bool(
            HEADING.match(line)
            or RULE.match(line)
            or line.lstrip().startswith(("```", ">"))
            or LIST_ITEM.match(line)
        )

    while i < len(lines):
        line = lines[i]

        if not line.strip():
            i += 1
            continue

        if line.lstrip().startswith("```"):
            fence = line.lstrip()[:3]
            lang = line.lstrip()[3:].strip()
            body = []
            i += 1
            while i < len(lines) and not lines[i].lstrip().startswith(fence):
                body.append(lines[i])
                i += 1
            i += 1
            cls = f' class="language-{html.escape(lang)}"' if lang else ""
            out.append(f"<pre><code{cls}>{html.escape(chr(10).join(body))}</code></pre>")
            continue

        m = HEADING.match(line)
        if m:
            level = len(m.group(1))
            content = render_inline(m.group(2))
            headings.append((level, content))
            if level > 1:
                out.append(f'<h{level} id="{slugify(content)}">{content}</h{level}>')
            i += 1
            continue

        if RULE.match(line):
            out.append("<hr />")
            i += 1
            continue

        if line.lstrip().startswith(">"):
            quoted = []
            while i < len(lines) and lines[i].strip():
                quoted.append(re.sub(r"^\s*>\s?", "", lines[i]))
                i += 1
            inner, _ = render_blocks(quoted)
            out.append(f"<blockquote>\n{inner}\n</blockquote>")
            continue

        m = LIST_ITEM.match(line)
        if m:
            ordered = m.group(1)[0].isdigit()
            items = []
            while i < len(lines):
                m = LIST_ITEM.match(lines[i])
                if m:
                    items.append(m.group(2))
                elif lines[i].strip() and not is_block_start(lines[i]):
                    items[-1] += " " + lines[i].strip()  # Continuation line.
                else:
                    break
                i += 1
            tag = "ol" if ordered else "ul"
            lis = "\n".join(f"<li>{render_inline(item)}</li>" for item in items)
            out.append(f"<{tag}>\n{lis}\n</{tag}>")
            continue

        para = []
        while i < len(lines) and lines[i].strip() and not is_block_start(lines[i]):
            para.append(lines[i].strip())
            i += 1
        out.append(f"<p>{render_inline(' '.join(para))}</p>")

    return "\n".join(out), headings


# ---------------------------------------------------------------------------
# Articles
# ---------------------------------------------------------------------------


def parse_front_matter(text):
    meta = {}
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            for line in text[4:end].splitlines():
                if ":" in line:
                    key, value = line.split(":", 1)
                    meta[key.strip().lower()] = value.strip().strip("\"'")
            text = text[end + 4 :].lstrip("\n")
    return meta, text


def parse_date(value, path):
    for fmt in ("%B %d, %Y", "%b %d, %Y", "%Y-%m-%d", "%d %B %Y"):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            pass
    sys.exit(f"build_articles: {path}: can't read date {value!r}")


def display_date(d):
    return f"{d.strftime('%B')} {d.day}, {d.year}"


def load_article(path, staged):
    meta, body = parse_front_matter(read_source(path, staged))
    if meta.get("draft", "").lower() in ("true", "yes"):
        return None

    content, headings = render_blocks(body.split("\n"))

    title = meta.get("title")
    title_html = render_inline(title) if title else None
    if not title_html:
        h1 = next((h for level, h in headings if level == 1), None)
        if not h1:
            sys.exit(f"build_articles: {path}: needs a '# Title' or title: field")
        title_html = h1

    description = meta.get("description")
    if description:
        description = plain_text(render_inline(description))
    else:
        first = re.search(r"<p>(.*?)</p>", content, re.S)
        description = plain_text(first.group(1)) if first else ""

    if "date" not in meta:
        sys.exit(f"build_articles: {path}: front matter needs a date")

    slug = os.path.splitext(os.path.basename(path))[0]
    return {
        "source": path,
        "slug": slug,
        "title_html": title_html,
        "title": plain_text(title_html),
        "author": meta.get("author", "Adam Byle"),
        "date": parse_date(meta["date"], path),
        "description": description,
        "content": content,
    }


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------


def page(title, description, depth, body, source):
    prefix = "../" * depth
    version = asset_version(STYLESHEET)
    css = f"{prefix}{STYLESHEET}" + (f"?v={version}" if version else "")
    meta = (
        "\n" + " " * 8
        + f'<meta name="description" content="{html.escape(description)}" />'
        if description
        else ""
    )
    return f"""<!doctype html>
<!-- {GENERATED_MARKER} from {source}. Edit the source, not this file. -->
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
        />
        <title>{html.escape(title)}</title>{meta}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="{FONTS_URL}" />
        <link rel="stylesheet" type="text/css" href="{css}" />
    </head>

    <body>
        <main class="page page-narrow">
            <nav class="site-nav" aria-label="Site">
                <a class="site-nav-home" href="{prefix}">Adam Byle</a>
                <a href="{prefix}{OUTPUT_DIR}/">Articles</a>
            </nav>
{body}
        </main>
    </body>
</html>
"""


def indent(text, spaces):
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.split("\n"))


def article_page(a):
    body = f"""<article class="article">
    <header class="article-header">
        <h1 class="article-title">{a["title_html"]}</h1>
        <p class="article-meta">
            {html.escape(a["author"])} ·
            <time datetime="{a["date"].isoformat()}">{display_date(a["date"])}</time>
        </p>
    </header>
    <div class="prose">
{indent(a["content"], 8)}
    </div>
</article>"""
    return page(
        f'{a["title"]} · Adam Byle',
        a["description"],
        2,
        indent(body, 12),
        a["source"],
    )


def index_page(articles):
    items = "\n".join(
        f"""<li>
    <a class="post" href="{a["slug"]}/">
        <time class="post-date" datetime="{a["date"].isoformat()}">{display_date(a["date"])}</time>
        <h2 class="post-title">{a["title_html"]}</h2>
        <p class="post-excerpt">{html.escape(a["description"], quote=False)}</p>
    </a>
</li>"""
        for a in articles
    )
    body = f"""<h1 class="article-title">Articles</h1>
<ul class="post-list">
{indent(items, 4)}
</ul>"""
    return page(
        "Articles · Adam Byle",
        None,
        1,
        indent(body, 12),
        f"{SOURCE_DIR}/*.md",
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def is_generated(path):
    try:
        with open(path, encoding="utf-8") as f:
            return GENERATED_MARKER in f.read(400)
    except OSError:
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--staged", action="store_true", help="read sources from the git index"
    )
    args = parser.parse_args()

    articles = [load_article(p, args.staged) for p in list_sources(args.staged)]
    articles = [a for a in articles if a]
    articles.sort(key=lambda a: (a["date"], a["slug"]), reverse=True)

    for a in articles:
        write(f"{OUTPUT_DIR}/{a['slug']}/index.html", article_page(a))
    write(f"{OUTPUT_DIR}/index.html", index_page(articles))

    # Remove pages for articles that were deleted, renamed, or made drafts.
    slugs = {a["slug"] for a in articles}
    out_dir = os.path.join(ROOT, OUTPUT_DIR)
    for name in os.listdir(out_dir):
        page_path = os.path.join(out_dir, name, "index.html")
        if name not in slugs and is_generated(page_path):
            shutil.rmtree(os.path.join(out_dir, name))
            print(f"build_articles: removed {OUTPUT_DIR}/{name}/")

    print(f"build_articles: built {len(articles)} article(s)")


if __name__ == "__main__":
    main()
